#Adrian Alfajri - 064002200009
import math
print('Penjumlahan')
print('')
a = int(input('Masukkan angka pertama : '))
b = int(input('Masukkan angka kedua : '))
n = a + b
print('')
print ('Hasil penjumlahan', a ,'dan', b ,'adalah', n) 
print('')
print('Pengurangan/selisih')
print('')
a = int(input('Masukkan angka pertama : '))
b = int(input('Masukkan angka kedua : '))
n = a - b
print('')
print ('Hasil selisih', a ,'dan', b ,'adalah', n)
print('')
print('Perkalian')
print('')
a = float(input('Masukkan angka pertama : '))
b = float(input('Masukkan angka kedua : '))
n = a * b
print('')
print ('Hasil kali', a ,'dan', b ,'adalah', n)
print('')
print('Modulo')
print('')
a = float(input('Masukkan angka pertama : '))
b = float(input('Masukkan angka kedua : '))
n = a % b
print('')
print ('Hasil sisa pembagian', a ,'dan', b ,'adalah', n)
print('')
print('Pembagian')
print('')
a = float(input('Masukkan angka pertama : '))
b = float(input('Masukkan angka kedua : '))
n = a / b
print('')
print ('Hasil bagi', a ,'dan', b ,'adalah', n)
print('')
print('Logaritma')
print('')
x = float(input('Masukkan angka : '))
print('')
print ('Hasil dari log', x , 'adalah', math.log(x))
print('')
print('Pemangkatan')
print('')
a = int(input('Masukkan angka : '))
b = int(input('Masukkan pangkat : '))
n = a ** b
print('')
print ('Hasil', a ,'pangkat', b ,'adalah', n)
print ('')
print ('')
print ('')
print ('')
print ('Terimakasih semoga harimu menyenangkan')
         